name: release
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest
    env:
      src-dir: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Find and replace in strings
      uses: LarsenLP/actions-find-and-replace-string@v3
      id: findandreplace
      with:
        source: ${{github.ref_name}}
        find: 'v'
        replace: ''
    - name: Publish with powershell
      run:
        .\publish.ps1 'Simpleverse.Bicep' './src/manifest.psd1' './src/*.*' '${{ steps.findandreplace.outputs.value }}' '${{secrets.psgallery_api_key}}'