name: release-test
on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: windows-latest
    env:
      src-dir: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Find and replace in strings
      uses: LarsenLP/actions-find-and-replace-string@v3
      id: findandreplace
      with:
        source: ${{github.ref_name}}
        find: 'v'
        replace: ''
    - name: Publish with powershell
      run:
        .\Publish-SimpleverseBicep.ps1 -v '${{ steps.findandreplace.outputs.value }}' -ak '${{secrets.psgallery_api_key}}'