name: release
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest
    env:
      src-dir: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Find and replace in strings
      uses: LarsenLP/actions-find-and-replace-string@v3
      id: findandreplace
      with:
        source: ${{github.ref_name}}
        find: 'v'
        replace: ''              
    - name: Replace in files
      uses: richardrigutins/replace-in-files@v2.1.8
      with:
        files: 'src/Simpleverse-Bicep.psd1'
        # The text that will replace the matched text.
        replacement-text: ${{ steps.findandreplace.outputs.value }}
        # The text that will be replaced.
        search-text: 'ModuleVersionNumber'
    - name: Read psd1
      id: manifest
      uses: jaywcjlove/github-action-read-file@main
      with:
        path: 'src/Simpleverse-Bicep.psd1'
    - name: Echo psd1
      run: echo "${{ steps.package.outputs.content }}"
    - name: Publish Package
      run: Publish-Module -Name src/Simpleverse-Bicep.psd1 -NuGetApiKey ${{secrets.psgallery_api_key}}
      working-directory: ${{env.src-dir}}
