name: release
on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: windows-latest
    env:
      src-dir: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Find and replace in strings
        uses: LarsenLP/actions-find-and-replace-string@v3
        id: findandreplace
        with:
          source: ${{github.ref_name}}
          find: 'v'
          replace: ''
      - name: Replace in files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: src/Simpleverse-Bicep.psd1
          replacement-text: "'v1.0.0'"
          search-text: <ModuleVersionNumber>
      - name: Read psd1
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: 'src/Simpleverse-Bicep.psd1'
      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: src/Simpleverse-Bicep.psd1
          old-string: <ModuleVersionNumber>
          new-string: "'v1.0.0'"
      - name: Read psd1
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: 'src/Simpleverse-Bicep.psd1'
